### PR TITLE
Itkv5

### PR DESCRIPTION
**Pull request by thewtex**
@lorensen @jhlegaretta Please take a look.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex 

Building **as a remote module**, I was **able to reproduce the error** mentioned by @melrobin for the previous commit hash in MSVC 2015 against the current ITK master.

I was **unable** to reproduce it building **as an external module**, though, since the CMake configuration was failing due to line
```
include(${ITK_SOURCE_DIR}/CMake/UseITK.cmake)
```

Anyway, now, the latest master (i.e. after the fixes by @thewtex), and building **as a remote module**, generates and **builds OK** 🎆 . 

However, when trying to **build as an external project**, generates OK, but :worried: I am getting **errors**:
- **KWStyle issues** at [itkFlatStructuringElement.h:229](https://github.com/InsightSoftwareConsortium/ITK/blob/a6132b8dbe4ac91fb718bc3103b64c90fd4e40a6/Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.h#L229)
```
Error	C2719	'radius': formal parameter with requested alignment of 8 won't be aligned	SkullStripHeaderTest1
```
and at some other lines.

Unchecking the Kitware Style in CMake solves the above.

- **Build errors** at [itkMathDetail.h:280](https://github.com/InsightSoftwareConsortium/ITK/blob/fca4ee27732429a24eb64b5a7ec4ecc41404a0ac/Modules/Core/Common/include/itkMathDetail.h#L280)
```
Error	C3861	'_mm_cvtsd_si64': identifier not found	SkullStripHeaderTest1
```
and [itkMathDetail.h:288](https://github.com/InsightSoftwareConsortium/ITK/blob/fca4ee27732429a24eb64b5a7ec4ecc41404a0ac/Modules/Core/Common/include/itkMathDetail.h#L288)
```
Error	C3861	'_mm_cvtss_si64': identifier not found	SkullStripHeaderTest1
```

BTW, the corresponding flags (KW Style and testing) are not present/exported when building as a remote module :thinking:

**Comment by thewtex** [comment]
@jhlegarreta Maybe a clean build is required?

**Comment by jhlegarreta** [comment]
@thewtex my bad: I had chosen different (default vs. `Win64`) generators for both `ITK` and `SkullStrip` in `CMake`. Sorry.

Now it's building OK :fireworks: , except for `SkullStripHeaderTest1`, which still yields an error related to Python/ITK Maintenance scripts:
```
Generating test/SkullStripHeaderTest1.cxx
Traceback (most recent call last):
  File "C:/SDKs/ITK/itk-head/ITK/CMake/../Utilities/Maintenance/BuildHeaderTest.py", line 139, in <module>
    ret = main()
  File "C:/SDKs/ITK/itk-head/ITK/CMake/../Utilities/Maintenance/BuildHeaderTest.py", line 110, in main
    test_src = open(test_source_file, 'w')
PermissionError: [Errno 13] Permission denied: 'C:/Binaries/SkullStrip\\test\\SkullStripHeaderTest1.cxx'

```

The last path does not seem to be correct. May be there is something to check in [BuildHeaderTest.py](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/BuildHeaderTest.py) or I am missing something?

**Comment by thewtex** [comment]
> PermissionError: [Errno 13] Permission denied:

Maybe it needs to be run as administrator?

**Comment by jhlegarreta** [comment]
@thewtex nope; I do have admin rights, it's the path that was malformed. In any case, it looks like the error got solved since my local build is now successful :-S

Weird.

So until it is reported again or some side-effect is reported, we can leave this as a false positive.

**Pull request merged**
